#!/bin/sh
script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
# Allow the existing network workers to request scheduling priority.
path_to_setcap=$(which setcap)
if [ -x "$script_dir/sunshine" ]; then
  path_to_sunshine=$(readlink -f "$script_dir/sunshine")
else
  path_to_sunshine=$(readlink -f "$(which sunshine)")
fi
if [ -x "$path_to_setcap" ] ; then
  echo "Setting CAP_SYS_NICE capabilities on Sunshine binary."
  echo "$path_to_setcap cap_sys_nice+p $path_to_sunshine"
  $path_to_setcap cap_sys_nice+p "$path_to_sunshine"
  echo "CAP_SYS_NICE capabilities set on Sunshine binary."
else
  echo "error: setcap not found or not executable."
fi
